// Privacy Policy (Server Component) — required for MiniPay listing.
// Placeholder legal copy; replace with reviewed text before launch.
import type { Metadata } from "next";
import { APP_NAME } from "@/lib/copy";

export const metadata: Metadata = {
  title: `Privacy — ${APP_NAME}`,
};

export default function PrivacyPage() {
  return (
    <article className="prose prose-sm max-w-none px-4 py-6 text-gray-700">
      <h1 className="text-lg font-bold text-gray-900">Privacy Policy</h1>
      <p className="mt-2 text-xs text-gray-400">Last updated: 2026-06-22</p>

      <h2 className="mt-5 text-sm font-semibold text-gray-900">
        1. What we process
      </h2>
      <p className="mt-1 text-sm">
        {APP_NAME} reads your public wallet address from MiniPay to check your
        on-chain subscription status and to apply free-tier summary quotas. We do
        not ask you to sign messages and we do not collect your phone number,
        name, or other personal identifiers.
      </p>

      <h2 className="mt-5 text-sm font-semibold text-gray-900">
        2. On-chain data
      </h2>
      <p className="mt-1 text-sm">
        Subscription transactions are public on the Celo blockchain by design.
        Your wallet address and subscription activity are visible on-chain to
        anyone; this is inherent to the service and outside our control.
      </p>

      <h2 className="mt-5 text-sm font-semibold text-gray-900">
        3. Usage analytics
      </h2>
      <p className="mt-1 text-sm">
        We collect aggregate, non-identifying usage metrics (such as active-user
        counts) to operate and improve the service and to report anonymized
        statistics on our Stats page.
      </p>

      <h2 className="mt-5 text-sm font-semibold text-gray-900">
        4. Third parties
      </h2>
      <p className="mt-1 text-sm">
        News content is sourced from public RSS feeds and AI summaries are
        generated by a third-party model provider. We do not sell your data.
      </p>

      <h2 className="mt-5 text-sm font-semibold text-gray-900">5. Contact</h2>
      <p className="mt-1 text-sm">
        For privacy questions, use the in-app Support link.
      </p>
    </article>
  );
}
