// Privacy Policy (Server Component) — required for MiniPay listing.
// Placeholder legal copy; replace with reviewed text before launch.
// Editorial Celiq styling.
import type { Metadata } from "next";
import { APP_NAME } from "@/lib/copy";

export const metadata: Metadata = {
  title: `Privacy — ${APP_NAME}`,
};

export default function PrivacyPage() {
  return (
    <article className="px-4 py-7">
      <div className="text-[10.5px] font-semibold uppercase tracking-[0.09em] text-accent">
        Legal
      </div>
      <h1 className="font-newsreader mt-1 text-[28px] font-bold leading-[1.08] tracking-[-0.02em] text-ink">
        Privacy Policy
      </h1>
      <p className="font-plex-mono num mt-2 text-[11px] uppercase tracking-[0.06em] text-ink-muted">
        Last updated: 2026-06-22
      </p>

      <Section title="1. What we process">
        {APP_NAME} reads your public wallet address from MiniPay to check your
        on-chain subscription status and to apply free-tier summary quotas. We do
        not ask you to sign messages and we do not collect your phone number,
        name, or other personal identifiers.
      </Section>

      <Section title="2. On-chain data">
        Subscription transactions are public on the Celo blockchain by design.
        Your wallet address and subscription activity are visible on-chain to
        anyone; this is inherent to the service and outside our control.
      </Section>

      <Section title="3. Usage analytics">
        We collect aggregate, non-identifying usage metrics (such as active-user
        counts) to operate and improve the service and to report anonymized
        statistics on our Stats page.
      </Section>

      <Section title="4. Third parties">
        News content is sourced from public RSS feeds and AI summaries are
        generated by a third-party model provider. We do not sell your data.
      </Section>

      <Section title="5. Contact">
        For privacy questions, use the in-app Support link.
      </Section>
    </article>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-6 border-t-[0.5px] border-rule pt-4">
      <h2 className="text-[13px] font-semibold text-ink">{title}</h2>
      <p className="mt-1.5 text-[14px] leading-[1.6] text-ink-2">{children}</p>
    </section>
  );
}
