// Centralized, MiniPay-compliant UI strings.
//
// Copy rules (enforced at MiniPay review): use "Network fee", "Deposit",
// "Withdraw", "Stablecoin" / "Digital dollar". NEVER use gas / onramp / offramp /
// crypto in anything a user sees. Never show a raw 0x… as the primary identifier.
export const APP_NAME = "MiniCeliq";
export const APP_TAGLINE = "Stablecoin & macro news, summarized.";

export const copy = {
  app: {
    name: APP_NAME,
    tagline: APP_TAGLINE,
  },
  nav: {
    feed: "News",
    stats: "Stats",
  },
  openInMiniPay: {
    title: "Open in MiniPay",
    body: "MiniCeliq runs inside the MiniPay app. Open it from your MiniPay Mini Apps tab to continue.",
    cta: "Open MiniPay",
  },
  loading: "Loading…",
  feed: {
    title: "Today's brief",
    empty: "No stories right now. Check back soon.",
    error: "Couldn't load the feed. Pull to refresh.",
    readSummary: "AI summary",
  },
  summary: {
    title: "AI summary",
    generating: "Summarizing…",
    error: "Couldn't generate a summary. Try again.",
    poweredBy: "Generated by AI — verify before acting.",
  },
  paywall: {
    title: "You've used today's free summaries",
    body: "Subscribe for unlimited AI summaries and a daily curated brief.",
    cta: "See plans",
    freeNote: "Free plan: full headlines + a few summaries each day.",
  },
  subscribe: {
    title: "Subscribe",
    monthly: "Monthly",
    yearly: "Yearly",
    perMonth: "/mo",
    perYear: "/yr",
    promoBadge: "Launch promo",
    payWith: "Pay with",
    networkFeeNote: "Network fee is paid automatically in your stablecoin.",
    // Two-step flow labels (approve then subscribe).
    stepApprove: "Approving stablecoin…",
    stepSubscribe: "Confirming subscription…",
    confirm: "Subscribe",
    success: "You're subscribed! Enjoy unlimited summaries.",
    error: "Something went wrong. No charge was made if it failed.",
    lowBalance: "Top up your balance to subscribe.",
    deposit: "Deposit",
    notConfigured: "Subscriptions open soon.",
    activeTitle: "You're subscribed",
    activeUntil: "Active until",
  },
  support: {
    label: "Support",
    aria: "Contact support",
  },
  legal: {
    terms: "Terms",
    privacy: "Privacy",
  },
} as const;
