// Centralized, MiniPay-compliant UI strings.
//
// Copy rules (enforced at MiniPay review): use "Network fee", "Deposit",
// "Withdraw", "Stablecoin" / "Digital dollar". NEVER use gas / onramp / offramp /
// crypto in anything a user sees. Never show a raw 0x… as the primary identifier.
export const APP_NAME = "MiniCeliq";
export const APP_TAGLINE = "Stablecoin & macro news, summarized.";

export const copy = {
  app: {
    name: APP_NAME,
    tagline: APP_TAGLINE,
  },
  nav: {
    feed: "News",
  },
  openInMiniPay: {
    title: "Open in MiniPay",
    body: "MiniCeliq runs inside the MiniPay app. Open it from your MiniPay Mini Apps tab to continue.",
    cta: "Open MiniPay",
  },
  loading: "Loading…",
  feed: {
    title: "Today's brief",
    empty: "No stories right now. Check back soon.",
    error: "Couldn't load the feed. Pull to refresh.",
    readSummary: "AI summary",
    // Mode tabs — the feed's view selector (replaces the old mixed chip bar).
    modeLatest: "Latest",
    modeForYou: "For You",
    modeSaved: "Saved",
    modeAria: "Switch feed view",
    // Slim toolbar: headline search + a Filter button that opens the FilterSheet.
    searchPlaceholder: "Search headlines",
    searchAria: "Search headlines by title",
    searchClear: "Clear search",
    filterButton: "Filter",
    // Spoken as e.g. "Filter, 2 active" — count of category/tone filters applied.
    filterActiveAria: "active",
    noMatches: "No headlines match these filters.",
    // FilterSheet — bottom sheet holding the category + tone selectors.
    filterTitle: "Filters",
    filterCategory: "Category",
    filterTone: "Tone",
    filterAll: "All",
    filterClear: "Clear",
    filterDone: "Done",
    // Saved view — your bookmarked stories (a mode tab).
    savedEmpty: "No saved articles yet — tap Save on a story.",
    // For You — a personalized feed filtered to the topics you choose, persisted
    // locally (a mode tab). Tone + search still compose; category is the interests.
    // Inline interest picker, shown when no topics are chosen yet (or on Edit).
    forYouPrompt: "Pick the topics you follow — we'll tune your feed to them.",
    forYouDone: "Done",
    forYouTopics: "Your topics",
    forYouEdit: "Edit topics",
    forYouEmpty: "Nothing in your topics right now. Tap Edit to follow more.",
    // Pagination — the Latest / For You feeds page 10 headlines at a time.
    // Rendered as: `${page} N ${pageOf} M` → "Page 1 of 5".
    prev: "Previous",
    next: "Next",
    page: "Page",
    pageOf: "of",
    prevAria: "Previous page",
    nextAria: "Next page",
  },
  summary: {
    title: "AI summary",
    generating: "Summarizing…",
    error: "Couldn't generate a summary. Try again.",
    // Kicker for the implication block (Celiq's "Artinya", in English).
    whatItMeans: "What it means",
    poweredBy: "Generated by AI — verify before acting.",
    readOriginal: "Read original",
    // Article actions.
    share: "Share",
    copyLink: "Copy original link",
    copied: "Original link copied ✓",
    // Save / bookmark toggle — keeps a story in your Saved list.
    save: "Save",
    saved: "Saved",
    saveAria: "Save this article",
    unsaveAria: "Remove from saved",
  },
  // Morning Brief — a once-daily AI digest, a perk for on-chain subscribers.
  brief: {
    kicker: "Morning Brief",
    title: "Morning Brief",
    // Shown to non-subscribers in the locked card.
    lockedTitle: "Today's Brief",
    lockedHint: "A once-daily digest of the day's top stories — for subscribers.",
    unlockCta: "Unlock today's brief",
    loading: "Writing today's brief…",
    poweredBy: "Curated by AI from today's headlines.",
  },
  paywall: {
    title: "You've used today's free summaries",
    body: "Subscribe for unlimited AI summaries and a daily curated brief.",
    cta: "See plans",
    freeNote: "Free plan: full headlines + a few summaries each day.",
  },
  subscribe: {
    title: "Subscribe",
    monthly: "Monthly",
    yearly: "Yearly",
    perMonth: "/mo",
    perYear: "/yr",
    promoBadge: "Launch promo",
    payWith: "Pay with",
    networkFeeNote: "Network fee is paid automatically in your stablecoin.",
    // Two-step flow labels (approve then subscribe).
    stepApprove: "Approving stablecoin…",
    stepSubscribe: "Confirming subscription…",
    confirm: "Subscribe",
    success: "You're subscribed! Enjoy unlimited summaries.",
    error: "Something went wrong. No charge was made if it failed.",
    lowBalance: "Top up your balance to subscribe.",
    deposit: "Deposit",
    notConfigured: "Subscriptions open soon.",
    activeTitle: "You're subscribed",
    activeUntil: "Active until",
  },
  // Renewal nudge — only surfaces in the final week of an active subscription.
  renewal: {
    // Used as: `${expiresIn} N ${day|days}`.
    expiresIn: "Your subscription expires in",
    day: "day",
    days: "days",
    cta: "Renew",
  },
  // CENY reward token — a perk minted to the subscriber on every subscribe.
  reward: {
    earn: "Earn",
    unit: "CENY",
    youHold: "You hold",
  },
  support: {
    label: "Support",
    aria: "Contact support",
  },
  legal: {
    terms: "Terms",
    privacy: "Privacy",
  },
} as const;
