// Centralized, MiniPay-compliant UI strings.
//
// Copy rules (enforced at MiniPay review): use "Network fee", "Deposit",
// "Withdraw", "Stablecoin" / "Digital dollar". NEVER use gas / onramp / offramp /
// crypto in anything a user sees. Never show a raw 0x… as the primary identifier.
export const APP_NAME = "MiniCeliq";
export const APP_TAGLINE = "Stablecoin & macro news, summarized.";

export const copy = {
  app: {
    name: APP_NAME,
    tagline: APP_TAGLINE,
  },
  nav: {
    feed: "News",
  },
  openInMiniPay: {
    title: "Open in MiniPay",
    body: "MiniCeliq runs inside the MiniPay app. Open it from your MiniPay Mini Apps tab to continue.",
    cta: "Open MiniPay",
  },
  loading: "Loading…",
  feed: {
    title: "Today's brief",
    empty: "No stories right now. Check back soon.",
    error: "Couldn't load the feed. Pull to refresh.",
    readSummary: "AI summary",
    // Filter chip bar above the headline list.
    filterAll: "All",
    filterAria: "Filter headlines by topic",
    // Sentiment filter — a second, distinct dimension below the topic chips.
    sentimentLabel: "Tone",
    sentimentAll: "All",
    sentimentAria: "Filter headlines by market tone",
    // Headline search (composes with the topic + tone filters).
    searchPlaceholder: "Search headlines",
    searchAria: "Search headlines by title",
    searchClear: "Clear search",
    noMatches: "No headlines match these filters.",
    // Saved articles — a leading filter chip that swaps in your bookmarked stories.
    savedFilter: "Saved",
    savedAria: "Show saved articles",
    savedEmpty: "No saved articles yet — tap Save on a story.",
  },
  summary: {
    title: "AI summary",
    generating: "Summarizing…",
    error: "Couldn't generate a summary. Try again.",
    poweredBy: "Generated by AI — verify before acting.",
    readOriginal: "Read original",
    // Article actions.
    share: "Share",
    copyLink: "Copy original link",
    copied: "Original link copied ✓",
    // Save / bookmark toggle — keeps a story in your Saved list.
    save: "Save",
    saved: "Saved",
    saveAria: "Save this article",
    unsaveAria: "Remove from saved",
  },
  // Morning Brief — a once-daily AI digest, a perk for on-chain subscribers.
  brief: {
    kicker: "Morning Brief",
    title: "Morning Brief",
    // Shown to non-subscribers in the locked card.
    lockedTitle: "Today's Brief",
    lockedHint: "A once-daily digest of the day's top stories — for subscribers.",
    unlockCta: "Unlock today's brief",
    loading: "Writing today's brief…",
    poweredBy: "Curated by AI from today's headlines.",
  },
  paywall: {
    title: "You've used today's free summaries",
    body: "Subscribe for unlimited AI summaries and a daily curated brief.",
    cta: "See plans",
    freeNote: "Free plan: full headlines + a few summaries each day.",
  },
  subscribe: {
    title: "Subscribe",
    monthly: "Monthly",
    yearly: "Yearly",
    perMonth: "/mo",
    perYear: "/yr",
    promoBadge: "Launch promo",
    payWith: "Pay with",
    networkFeeNote: "Network fee is paid automatically in your stablecoin.",
    // Two-step flow labels (approve then subscribe).
    stepApprove: "Approving stablecoin…",
    stepSubscribe: "Confirming subscription…",
    confirm: "Subscribe",
    success: "You're subscribed! Enjoy unlimited summaries.",
    error: "Something went wrong. No charge was made if it failed.",
    lowBalance: "Top up your balance to subscribe.",
    deposit: "Deposit",
    notConfigured: "Subscriptions open soon.",
    activeTitle: "You're subscribed",
    activeUntil: "Active until",
  },
  // Renewal nudge — only surfaces in the final week of an active subscription.
  renewal: {
    // Used as: `${expiresIn} N ${day|days}`.
    expiresIn: "Your subscription expires in",
    day: "day",
    days: "days",
    cta: "Renew",
  },
  // CENY reward token — a perk minted to the subscriber on every subscribe.
  reward: {
    earn: "Earn",
    unit: "CENY",
    youHold: "You hold",
  },
  support: {
    label: "Support",
    aria: "Contact support",
  },
  legal: {
    terms: "Terms",
    privacy: "Privacy",
  },
} as const;
